# Generated by Django 4.2.7 on 2024-02-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
